version: '2'
services:
  riki:
    image: riki:0.0.1
    ports:
      - '5002:5002'
    volumes:
      - 'riki_content:/opt/app/content'
      - './reports/cov_html:/opt/app/cov_html'
      - './reports/docs:/opt/app/wiki/web/static/docs'
    env_file:
      - .env
volumes:
  riki_content:
    driver: local
